name: Colorist Training
favicon: null
layout_spectrum: 0.92237
typography_spectrum: 0.007194906938821077
title: Colorist Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.779030793113634
  lightness: 0.7725524890702218
  saturation: 0.06060022790916264
  rhythmicContrast: 0.6980440195184201
purpose: []
